import { Inter } from 'next/font/google'
import "../app/globals.css"
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Product Listing',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel='icon'href='https://img.freepik.com/free-vector/realistic-silver-frame-template_23-2149247772.jpg'  ></link>
      </Head>
      <body className={inter.className}>
       {children}      
      </body>
    </html>
  )
}
